# -*- coding: utf-8 -*-
"""ML_Group8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1yzUsDBlQ2wlYLQbVTbRdkPz8ODYKAb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/gdrive')

data_path = '/content/gdrive/My Drive/ML_Final/vietnam_housing_dataset.csv'
df = pd.read_csv(data_path)
df.head()

df.info()

df.describe()

missing_percentage = df.isnull().sum() / len(df) * 100
print("Percentage of missing values per column:\n", missing_percentage)

columns_to_drop = ['Address', 'Balcony direction', 'House direction', 'Furniture state', 'Access Road']
df = df.drop(columns=columns_to_drop)
print(f"Dropped columns: {columns_to_drop}")

# Display the head of the updated DataFrame
print("\nDataFrame head after dropping columns:")
print(df.head())

# Display the info of the updated DataFrame
print("\nDataFrame info after dropping columns:")
df.info()

# Calculate and display the new percentage of missing values per column
print("\nNew percentage of missing values per column:")
print(df.isnull().sum() / len(df) * 100)

num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows before removal: {num_duplicates}")

df.drop_duplicates(inplace=True)
print("Duplicate rows removed.")

print(f"Number of rows after removing duplicates: {len(df)}")
num_duplicates_after_removal = df.duplicated().sum()
print(f"Number of duplicate rows after removal: {num_duplicates_after_removal}")

print("Current DataFrame info:")
df.info()

print("Unique values and their counts for 'Legal status' column:")
print(df['Legal status'].value_counts(dropna=False))

missing_percentage = df.isnull().sum() / len(df) * 100
print("Percentage of missing values per column after previous steps:\n", missing_percentage)

for col in ['Frontage', 'Floors', 'Bedrooms', 'Bathrooms']:
    df[col] = df[col].fillna(df[col].median())
print("Missing values in 'Frontage', 'Floors', 'Bedrooms', and 'Bathrooms' imputed with median.")

df['Legal status'] = df['Legal status'].fillna(df['Legal status'].mode()[0])
print("Missing values in 'Legal status' imputed with mode.")

print("Sum of null values per column after imputation:")
print(df.isnull().sum())

numerical_cols = ['Area', 'Frontage', 'Floors', 'Bedrooms', 'Bathrooms', 'Price']

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Apply capping
    df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
    df[col] = np.where(df[col] > upper_bound, upper_bound, df[col])

print("Outliers in numerical columns have been managed using capping.")

print("\nDescriptive statistics after outlier capping:")
print(df[numerical_cols].describe())

from sklearn.preprocessing import MinMaxScaler

numerical_cols = ['Area', 'Frontage', 'Floors', 'Bedrooms', 'Bathrooms', 'Price']

scaler = MinMaxScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

print("Numerical columns have been normalized using Min-Max scaling.")

print("\nDescriptive statistics after normalization:")
print(df[numerical_cols].describe())

print("\nDataFrame info after one-hot encoding (or attempted encoding):")
df.info()

print("\nDescriptive statistics of the DataFrame after one-hot encoding (or attempted encoding):")
print(df.describe())

print("\nColumns after one-hot encoding (or attempted encoding):")
print(df.columns)

import os

# Extract the directory and filename from the original data_path
parent_dir = os.path.dirname(data_path)
original_filename = os.path.basename(data_path)

# Create a new filename for the cleaned data
cleaned_filename = "SuperCleaned_" + original_filename
output_csv_path = os.path.join(parent_dir, cleaned_filename)

# Save the cleaned DataFrame to the specified path
df.to_csv(output_csv_path, index=False)

print(f"Cleaned data saved to: {output_csv_path}")

numerical_features = ['Area', 'Frontage', 'Floors', 'Bedrooms', 'Bathrooms']

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_features):
    plt.subplot(2, 3, i + 1)
    sns.scatterplot(x=df[col], y=df['Price'])
    plt.title(f'{col} vs. Price')
    plt.xlabel(col)
    plt.ylabel('Price (Normalized)')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(x='Legal status', y='Price', data=df)
plt.title('Price Distribution by Legal Status')
plt.xlabel('Legal Status')
plt.ylabel('Price (Normalized)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

numerical_features_for_pairplot = ['Area', 'Frontage', 'Floors', 'Bedrooms', 'Bathrooms', 'Price']
sns.pairplot(df[numerical_features_for_pairplot])
plt.suptitle('Pair Plot of Numerical Features', y=1.02) # Adjust title position
plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

numerical_cols = ['Area', 'Frontage', 'Floors', 'Bedrooms', 'Bathrooms', 'Price']
correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix of Numerical Features')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

numerical_cols = ['Area', 'Frontage', 'Floors', 'Bedrooms', 'Bathrooms', 'Price']

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(2, 3, i + 1) # Arrange plots in a 2x3 grid
    sns.histplot(df[col], kde=True, bins=30)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

"""# Task
Build and evaluate a Linear Regression model to predict 'Price' using the `df` DataFrame. This involves converting the 'Legal status' categorical column to a numerical format using one-hot encoding, splitting the data into training and testing sets, training the model, making predictions, and then calculating and interpreting Root Mean Squared Error (RMSE), R-squared (R2), and Mean Absolute Percentage Error (MAPE). Additionally, create a scatter plot comparing actual versus predicted prices with a perfect prediction line.
"""

df_encoded = pd.get_dummies(df, columns=['Legal status'], drop_first=True)
df_encoded[[col for col in df_encoded.columns if 'Legal status' in col]] = df_encoded[[col for col in df_encoded.columns if 'Legal status' in col]].astype(int)

X = df_encoded.drop('Price', axis=1)
y = df_encoded['Price']

print("Shape of X (features):", X.shape)
print("Shape of y (target):", y.shape)
print("First 5 rows of X:")
print(X.head())
print("First 5 rows of y:")
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")

y_pred = model.predict(X_test)

print("Predictions generated successfully.")
print("First 5 predictions:")
print(y_pred[:5])

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Calculate RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# Calculate R-squared
r2 = r2_score(y_test, y_pred)

# Calculate MAPE
# Avoid division by zero by adding a small epsilon or handling cases where y_test is zero
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    # Replace 0s in y_true with a small epsilon to avoid division by zero
    # Only if there are actual 0s, otherwise just use y_true
    non_zero_y_true = np.where(y_true == 0, np.finfo(float).eps, y_true)
    return np.mean(np.abs((y_true - y_pred) / non_zero_y_true)) * 100

mae = mean_absolute_error(y_test, y_pred)

print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R-squared (R2): {r2:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction Line')
plt.xlabel('Actual Prices (Normalized)')
plt.ylabel('Predicted Prices (Normalized)')
plt.title('Actual vs. Predicted Prices')
plt.legend()
plt.grid(True)
plt.show()

print("Scatter plot of Actual vs. Predicted Prices generated.")

"""## Final Task

### Subtask:
Summarize the performance of the Linear Regression model, discussing the calculated evaluation metrics and insights from the visualization.

## Summary:

### Q&A
The Linear Regression model's performance can be summarized as follows:
The model achieved an R-squared (\R^2$) of 0.2040, indicating that approximately 20.40% of the variance in 'Price' can be explained by the model's features. This suggests a relatively weak explanatory power. The Root Mean Squared Error (RMSE) was 0.1882, representing the typical magnitude of prediction errors. The Mean Absolute Percentage Error (MAPE) was extraordinarily high at 59679432480444.1641%, which strongly suggests an issue with the metric's applicability to the dataset, likely due to very small or zero actual 'Price' values leading to division by near-zero numbers. The scatter plot of actual versus predicted prices visually confirms that while there's a general trend, many predictions deviate significantly from the perfect prediction line.

### Data Analysis Key Findings
*   The 'Legal status' categorical column was successfully converted to numerical format using one-hot encoding, resulting in 6 features for the model.
*   The dataset was split into training (23,084 samples) and testing (5,772 samples) sets.
*   The trained Linear Regression model yielded a Root Mean Squared Error (RMSE) of 0.1882 on the test set.
*   The R-squared (\R^2$) value for the model was 0.2040, indicating that only about 20.40% of the variance in price is explained by the model.
*   The Mean Absolute Percentage Error (MAPE) was exceptionally high at 59679432480444.1641%, which points to potential issues with the metric's suitability for this dataset, likely due to small or zero actual values.
*   The scatter plot revealed that while the model captures some underlying trend, there is considerable scatter around the perfect prediction line, especially for higher prices.

### Insights or Next Steps
*   The low R-squared value suggests that the current set of features has limited predictive power for 'Price'. Further feature engineering, including exploring other relevant variables or transforming existing ones, is recommended.
*   The extraordinarily high MAPE necessitates a review of the 'Price' distribution in the dataset, especially for values near zero, and consideration of alternative error metrics that are more robust to such conditions.
"""



"""# Task
Train a Random Forest Regressor model to predict 'Price' using the prepared training and testing data (`X_train`, `X_test`, `y_train`, `y_test`). Subsequently, make predictions on the test set, calculate Root Mean Squared Error (RMSE), R-squared (R2), and Mean Absolute Percentage Error (MAPE), and generate a scatter plot to visualize actual versus predicted prices, including a perfect prediction line. Finally, summarize the Random Forest model's performance based on these metrics and the visualization, and compare its effectiveness to the previously evaluated Linear Regression model.
"""

print("Head of features (X):")
print(X.head())
print("\nData types and non-null values for features (X):")
X.info()
print("\nHead of target (y):")
print(y.head())

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.ensemble import RandomForestRegressor

# Instantiate the RandomForestRegressor model
# Using random_state for reproducibility
rf_model = RandomForestRegressor(random_state=42)

# Fit the model to the training data
rf_model.fit(X_train, y_train)

print("Random Forest Regressor model trained successfully.")

y_pred_rf = rf_model.predict(X_test)

print("Predictions generated successfully using Random Forest model.")
print("First 5 predictions:")
print(y_pred_rf[:5])

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Calculate RMSE
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))

# Calculate R-squared
r2_rf = r2_score(y_test, y_pred_rf)

# Calculate MAPE
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    # Replace 0s in y_true with a small epsilon to avoid division by zero
    non_zero_y_true = np.where(y_true == 0, np.finfo(float).eps, y_true)
    return np.mean(np.abs((y_true - y_pred) / non_zero_y_true)) * 100

mae_rf = mean_absolute_error(y_test, y_pred_rf)

print(f"Random Forest - Root Mean Squared Error (RMSE): {rmse_rf:.4f}")
print(f"Random Forest - R-squared (R2): {r2_rf:.4f}")
print(f"Random Forest - Mean Absolute Error (MAE): {mae_rf:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred_rf, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction Line')
plt.xlabel('Actual Prices (Normalized)')
plt.ylabel('Predicted Prices (Normalized)')
plt.title('Random Forest: Actual vs. Predicted Prices')
plt.legend()
plt.grid(True)
plt.show()

print("Scatter plot of Random Forest Actual vs. Predicted Prices generated.")

"""## Summary of Random Forest Model Performance and Comparison

The Random Forest Regressor model yielded the following evaluation metrics:
- **Root Mean Squared Error (RMSE):** 0.1877
- **R-squared (R2):** 0.2084
- **Mean Absolute Percentage Error (MAPE):** 66423190078883.9844%

### Comparison with Linear Regression Model:

**Linear Regression Model Metrics:**
- **RMSE:** 0.1882
- **R2:** 0.2040
- **MAPE:** 59679432480444.1641%

**Analysis:**

1.  **RMSE (Root Mean Squared Error):** The Random Forest model shows a slightly lower RMSE (0.1877) compared to the Linear Regression model (0.1882). This indicates that, on average, the Random Forest model's predictions are marginally closer to the actual values than those of the Linear Regression model.

2.  **R-squared (R2):** The R-squared value for the Random Forest model (0.2084) is also slightly higher than that of the Linear Regression model (0.2040). Both R2 values are relatively low, suggesting that neither model explains a large proportion of the variance in 'Price'. However, the Random Forest model still demonstrates a minor improvement in explained variance.

3.  **MAPE (Mean Absolute Percentage Error):** Both models exhibit extremely high MAPE values, which, as previously noted, is likely due to the presence of very small or zero 'Price' values in the normalized dataset leading to division by near-zero numbers. This metric is not reliable for comparison in this specific context without further investigation or adjustment.

4.  **Visualization (Actual vs. Predicted Prices):** Similar to the Linear Regression model, the scatter plot for the Random Forest model shows a general trend where predicted prices align with actual prices, but there is still considerable scatter, especially for higher prices. The Random Forest model might show slightly less dispersion or a better fit for certain data points due to its non-linear nature, but visually, the improvement over linear regression is not dramatic.

**Conclusion:**

Overall, the Random Forest Regressor model performs only marginally better than the Linear Regression model based on RMSE and R-squared. Both models struggle to explain a significant portion of the variance in the 'Price' target variable with the current set of features. The extremely high MAPE for both models suggests an issue with the metric's applicability, likely related to the normalization and potential presence of near-zero values in the target variable.

### Next Steps:

*   Investigate the target variable's distribution more closely, especially for values near zero, to understand the high MAPE. Consider alternative normalization techniques or target transformations if appropriate.
*   Explore feature engineering to create more predictive features.
*   Consider hyperparameter tuning for the Random Forest model to potentially improve its performance further.
*   Evaluate other regression models that might be more suitable for the dataset's characteristics.

## Summary:

### Q&A
The Random Forest Regressor model showed marginally better performance than the Linear Regression model. Its Root Mean Squared Error (RMSE) was 0.1877 compared to Linear Regression's 0.1882, indicating slightly more accurate predictions. The R-squared (R2) for Random Forest was 0.2084, slightly higher than Linear Regression's 0.2040, suggesting it explains a slightly larger, though still small, proportion of the variance in 'Price'. Both models exhibited extremely high Mean Absolute Percentage Error (MAPE) values, rendering this metric unreliable for comparison in this context.

### Data Analysis Key Findings
*   The Random Forest Regressor model was successfully trained and evaluated, yielding an RMSE of 0.1877, an R-squared of 0.2084, and a MAPE of 66423190078883.9844%.
*   When compared to the Linear Regression model, the Random Forest model achieved a slightly lower RMSE (0.1877 vs. 0.1882) and a slightly higher R-squared (0.2084 vs. 0.2040).
*   Both models showed very low R-squared values (around 0.20), indicating that neither model explains a large proportion of the variance in the 'Price' target variable with the current features.
*   The extremely high MAPE for both models (Random Forest: 66423190078883.9844%, Linear Regression: 59679432480444.1641%) is attributed to the presence of very small or zero 'Price' values in the normalized dataset, leading to division by near-zero numbers, making this metric unreliable.
*   The scatter plot for Random Forest, similar to Linear Regression, visually confirmed a general positive correlation between actual and predicted prices but also considerable scatter, suggesting struggles with precise predictions across the entire price range.

### Insights or Next Steps
*   Investigate the target variable's distribution more closely, especially for values near zero, and consider alternative normalization techniques or target transformations to address the high MAPE issue.
*   Explore feature engineering to create more predictive features or consider hyperparameter tuning for the Random Forest model to potentially improve its performance.
"""



"""# Task
Train an XGBoost Regressor model to predict 'Price' using the prepared training and testing data (`X_train`, `X_test`, `y_train`, `y_test`). Make predictions on the test set, calculate Root Mean Squared Error (RMSE), R-squared (R2), and Mean Absolute Percentage Error (MAPE), and generate a scatter plot to visualize actual versus predicted prices, including a perfect prediction line. Finally, summarize the XGBoost model's performance based on these metrics and the visualization, and compare its effectiveness to the previously evaluated Linear Regression and Random Forest models.
"""

print("\n--- Verifying features (X) ---")
print("First 5 rows of X:")
print(X.head())
print("\nShape of X:", X.shape)
print("\nData types and non-null values for X:")
X.info()

print("\n--- Verifying target (y) ---")
print("First 5 rows of y:")
print(y.head())
print("\nShape of y:", y.shape)
print("\nData type for y:", y.dtype)

from xgboost import XGBRegressor

# Instantiate the XGBRegressor model with random_state for reproducibility
xgb_model = XGBRegressor(random_state=42)

# Fit the model to the training data
xgb_model.fit(X_train, y_train)

print("XGBoost Regressor model trained successfully.")

y_pred_xgb = xgb_model.predict(X_test)

print("Predictions generated successfully using XGBoost model.")
print("First 5 predictions:")
print(y_pred_xgb[:5])

from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Calculate RMSE
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))

# Calculate R-squared
r2_xgb = r2_score(y_test, y_pred_xgb)

# Calculate MAPE (using the previously defined function)
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    non_zero_y_true = np.where(y_true == 0, np.finfo(float).eps, y_true)
    return np.mean(np.abs((y_true - y_pred) / non_zero_y_true)) * 100

mae_xgb = mean_absolute_error(y_test, y_pred_xgb)

print(f"XGBoost - Root Mean Squared Error (RMSE): {rmse_xgb:.4f}")
print(f"XGBoost - R-squared (R2): {r2_xgb:.4f}")
print(f"Mean Absolute Error (MAE): {mae_xgb:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred_xgb, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction Line')
plt.xlabel('Actual Prices (Normalized)')
plt.ylabel('Predicted Prices (Normalized)')
plt.title('XGBoost: Actual vs. Predicted Prices')
plt.legend()
plt.grid(True)
plt.show()

print("Scatter plot of XGBoost Actual vs. Predicted Prices generated.")

"""## Summary of XGBoost Model Performance and Comparison

The XGBoost Regressor model yielded the following evaluation metrics:
- **Root Mean Squared Error (RMSE):** 0.1757
- **R-squared (R2):** 0.3062
- **Mean Absolute Percentage Error (MAPE):** 58498323545338.9141%

### Comparison with Linear Regression and Random Forest Models:

**Linear Regression Model Metrics:**
- **RMSE:** 0.1882
- **R2:** 0.2040
- **MAPE:** 59679432480444.1641%

**Random Forest Model Metrics:**
- **RMSE:** 0.1877
- **R2:** 0.2084
- **MAPE:** 66423190078883.9844%

**Analysis:**

1.  **RMSE (Root Mean Squared Error):** The XGBoost model shows the lowest RMSE (0.1757) among all three models, indicating that its predictions are, on average, closer to the actual values compared to both Linear Regression (0.1882) and Random Forest (0.1877). This suggests a better overall predictive accuracy.

2.  **R-squared (R2):** The R-squared value for the XGBoost model (0.3062) is significantly higher than that of both Linear Regression (0.2040) and Random Forest (0.2084). This indicates that the XGBoost model explains a considerably larger proportion of the variance in 'Price' compared to the other two models, showing a more robust fit to the data.

3.  **MAPE (Mean Absolute Percentage Error):** All three models exhibit extremely high MAPE values. As noted previously, this is likely due to the presence of very small or zero 'Price' values in the normalized dataset leading to division by near-zero numbers. Therefore, MAPE is not a reliable metric for comparison in this specific context.

4.  **Visualization (Actual vs. Predicted Prices):** The scatter plot for the XGBoost model generally shows a stronger concentration of points around the perfect prediction line compared to the Linear Regression and Random Forest models. While there's still some scatter, especially for higher prices, the overall trend appears to be more aligned with accurate predictions.

**Conclusion:**

The XGBoost Regressor model clearly outperforms both the Linear Regression and Random Forest models in terms of RMSE and R-squared. It explains a greater proportion of the variance in the target variable and provides more accurate predictions on average. Despite its improved performance, the R-squared value of 0.3062 still suggests that there's a significant amount of variance in 'Price' that is not captured by the current features and model. The high MAPE remains an issue across all models, suggesting a need to re-evaluate the metric or target variable handling.

### Next Steps:

*   Further hyperparameter tuning for the XGBoost model could potentially yield even better results.
*   Continued investigation into the target variable's distribution and alternative error metrics or transformations is warranted to address the MAPE issue.
*   Feature engineering or the inclusion of additional relevant features could further improve the model's explanatory power and predictive accuracy.

## Final Task

### Subtask:
Summarize the performance of the XGBoost Regressor model, discussing the calculated evaluation metrics and insights from the visualization. Additionally, compare its effectiveness to the previously evaluated Linear Regression and Random Forest models.

## Summary:

### Q&A
The XGBoost Regressor model performed better than both Linear Regression and Random Forest models. It achieved the lowest Root Mean Squared Error (RMSE) at 0.1757 and the highest R-squared (R2) at 0.3062. The scatter plot visualization also indicated a stronger alignment of XGBoost's predictions with actual values compared to the other models. However, the Mean Absolute Percentage Error (MAPE) remained exceptionally high for all models, including XGBoost (58498323545338.9141%), suggesting an unreliability of this metric due to the normalized 'Price' values.

### Data Analysis Key Findings
*   The XGBoost Regressor model achieved a Root Mean Squared Error (RMSE) of 0.1757, which is lower than Linear Regression (0.1882) and Random Forest (0.1877).
*   The R-squared (R2) for the XGBoost model was 0.3062, significantly higher than Linear Regression (0.2040) and Random Forest (0.2084), indicating a better explanation of variance in 'Price'.
*   The Mean Absolute Percentage Error (MAPE) for XGBoost was extremely high at 58498323545338.9141%, similar to the other models, suggesting issues with the metric's applicability given the normalized target variable.
*   The visualization of actual versus predicted prices for XGBoost showed a stronger concentration of points around the perfect prediction line compared to the other models, reinforcing its improved performance.

### Insights or Next Steps
*   Further hyperparameter tuning for the XGBoost model could potentially enhance its performance.
*   Investigate alternative error metrics or transformations for the target variable to address the persistent issue with the Mean Absolute Percentage Error (MAPE).
*   Consider feature engineering or incorporating additional relevant features to further improve the model's explanatory power and predictive accuracy, as the current R-squared still indicates significant unexplained variance.
"""



"""# Task
Train a LightGBM Regressor model to predict 'Price' using the prepared training and testing data (`X_train`, `X_test`, `y_train`, `y_test`). Make predictions on the test set, calculate Root Mean Squared Error (RMSE), R-squared (R2), and Mean Absolute Error (MAE) for the LightGBM model's predictions, and generate a scatter plot to visualize actual versus predicted prices, including a perfect prediction line. Finally, summarize the LightGBM model's performance based on these metrics and the visualization, and compare its effectiveness to the previously evaluated Linear Regression, Random Forest, and XGBoost models.
"""

print("--- Verifying features (X) ---")
print("First 5 rows of X:")
print(X.head())
print("\nShape of X:", X.shape)
print("\nData types and non-null values for X:")
X.info()

print("\n--- Verifying target (y) ---")
print("First 5 rows of y:")
print(y.head())
print("\nShape of y:", y.shape)
print("\nData type for y:", y.dtype)

import lightgbm as lgb

# Instantiate the LightGBM Regressor model
# Using random_state for reproducibility
lgb_model = lgb.LGBMRegressor(random_state=42)

# Fit the model to the training data
lgb_model.fit(X_train, y_train)

print("LightGBM Regressor model trained successfully.")

y_pred_lgbm = lgb_model.predict(X_test)

print("Predictions generated successfully using LightGBM model.")
print("First 5 predictions:")
print(y_pred_lgbm[:5])

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

# Calculate RMSE
rmse_lgbm = np.sqrt(mean_squared_error(y_test, y_pred_lgbm))

# Calculate R-squared
r2_lgbm = r2_score(y_test, y_pred_lgbm)

# Calculate MAE
mae_lgbm = mean_absolute_error(y_test, y_pred_lgbm)

# Calculate MAPE (using the previously defined function)
def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    non_zero_y_true = np.where(y_true == 0, np.finfo(float).eps, y_true)
    return np.mean(np.abs((y_true - y_pred) / non_zero_y_true)) * 100

mape_lgbm = mean_absolute_percentage_error(y_test, y_pred_lgbm)

print(f"LightGBM - Root Mean Squared Error (RMSE): {rmse_lgbm:.4f}")
print(f"LightGBM - R-squared (R2): {r2_lgbm:.4f}")
print(f"LightGBM - Mean Absolute Error (MAE): {mae_lgbm:.4f}")
print(f"LightGBM - Mean Absolute Percentage Error (MAPE): {mape_lgbm:.4f}%")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred_lgbm, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction Line')
plt.xlabel('Actual Prices (Normalized)')
plt.ylabel('Predicted Prices (Normalized)')
plt.title('LightGBM: Actual vs. Predicted Prices')
plt.legend()
plt.grid(True)
plt.show()

print("Scatter plot of LightGBM Actual vs. Predicted Prices generated.")

"""## Summary of LightGBM Model Performance and Comparison

The LightGBM Regressor model yielded the following evaluation metrics:
- **Root Mean Squared Error (RMSE):** 0.1744
- **R-squared (R2):** 0.3167
- **Mean Absolute Error (MAE):** 0.1398
- **Mean Absolute Percentage Error (MAPE):** 47867669735322.0000%

### Comparison with Linear Regression, Random Forest, and XGBoost Models:

**Linear Regression Model Metrics:**
- **RMSE:** 0.1882
- **R2:** 0.2040
- **MAE:** 0.1537
- **MAPE:** 59679432480444.1641%

**Random Forest Model Metrics:**
- **RMSE:** 0.1877
- **R2:** 0.2084
- **MAE:** 0.1467
- **MAPE:** 66423190078883.9844%

**XGBoost Model Metrics:**
- **RMSE:** 0.1757
- **R2:** 0.3062
- **MAE:** 0.1404
- **MAPE:** 58498323545338.9141%

**Analysis:**

1.  **RMSE (Root Mean Squared Error):** The LightGBM model achieved the lowest RMSE (0.1744) among all models, indicating that its predictions are, on average, the closest to the actual values. This represents a slight improvement over XGBoost (0.1757) and a more significant improvement over Linear Regression (0.1882) and Random Forest (0.1877).

2.  **R-squared (R2):** LightGBM also shows the highest R-squared value (0.3167), meaning it explains the largest proportion of the variance in 'Price'. This is an improvement over XGBoost (0.3062) and substantially better than Linear Regression (0.2040) and Random Forest (0.2084).

3.  **MAE (Mean Absolute Error):** The LightGBM model exhibits the lowest MAE (0.1398), suggesting that its average absolute prediction error is minimal compared to the other models.

4.  **MAPE (Mean Absolute Percentage Error):** All models, including LightGBM, continue to show extremely high MAPE values. As previously discussed, this metric is likely unreliable due to the normalization of the 'Price' variable and the potential presence of near-zero actual values, which cause division by very small numbers.

5.  **Visualization (Actual vs. Predicted Prices):** The scatter plot for the LightGBM model reinforces the quantitative metrics. It generally shows a tighter clustering of predicted values around the perfect prediction line, indicating a better fit and more accurate predictions across the range of prices compared to the other models, especially Linear Regression and Random Forest.

**Conclusion:**

The LightGBM Regressor model demonstrates the best performance among the four models evaluated (Linear Regression, Random Forest, and XGBoost) in terms of RMSE, R-squared, and MAE. It is the most effective at capturing the underlying patterns in the data and predicting housing prices with the current feature set. However, the overall R-squared value of 0.3167 still indicates that a significant portion of the variance in 'Price' remains unexplained, suggesting room for further improvement.

### Next Steps:

*   Continue with hyperparameter tuning for the LightGBM model to optimize its performance further.
*   Address the MAPE issue by investigating the target variable's distribution near zero, considering alternative normalization techniques, or choosing evaluation metrics more robust to small values.
*   Explore advanced feature engineering techniques or consider integrating external datasets to enhance the model's predictive power and increase the explained variance in 'Price'.
"""



"""# Task
Perform hyperparameter tuning for the Random Forest Regressor model using GridSearchCV or RandomizedSearchCV to find the optimal set of parameters for improved performance.

## Hyperparameter Tuning for Random Forest

### Subtask:
Perform hyperparameter tuning for the Random Forest Regressor model using GridSearchCV or RandomizedSearchCV to find the optimal set of parameters for improved performance.

**Reasoning**:
To begin hyperparameter tuning, I will import the necessary libraries, define the parameter grid for `RandomForestRegressor`, and then instantiate `RandomizedSearchCV`.
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

# 2. Define the hyperparameter distributions
param_dist_rf = {
    'n_estimators': [100, 200, 300],
    'max_features': ['sqrt', None],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# 3. Instantiate a RandomForestRegressor model
rf_base_model = RandomForestRegressor(random_state=42)

# 4. Instantiate RandomizedSearchCV
random_search_rf = RandomizedSearchCV(
    estimator=rf_base_model,
    param_distributions=param_dist_rf,
    n_iter=10,  # Reduced n_iter for quicker execution in a demonstration; typically would be higher (e.g., 50 or 100)
    cv=3,       # Reduced cv for quicker execution; typically would be higher (e.g., 5)
    scoring='neg_mean_squared_error',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# 5. Fit RandomizedSearchCV to the training data
random_search_rf.fit(X_train, y_train)

# 6. Print the best parameters found
print("Best parameters for Random Forest:", random_search_rf.best_params_)

"""## Hyperparameter Tuning for XGBoost

### Subtask:
Perform hyperparameter tuning for the XGBoost Regressor model using GridSearchCV or RandomizedSearchCV to find the optimal set of parameters for improved performance.

"""

from xgboost import XGBRegressor

# 2. Define the hyperparameter distributions
param_dist_xgb = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0]
}

# 3. Instantiate an XGBRegressor model
xgb_base_model = XGBRegressor(random_state=42)

# 4. Instantiate RandomizedSearchCV
random_search_xgb = RandomizedSearchCV(
    estimator=xgb_base_model,
    param_distributions=param_dist_xgb,
    n_iter=10,  # Number of parameter settings that are sampled. Reduced for quicker execution.
    cv=3,       # Number of folds in cross-validation. Reduced for quicker execution.
    scoring='neg_mean_squared_error',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# 5. Fit RandomizedSearchCV to the training data
random_search_xgb.fit(X_train, y_train)

# 6. Print the best parameters found
print("Best parameters for XGBoost:", random_search_xgb.best_params_)

"""## Hyperparameter Tuning for LightGBM

### Subtask:
Perform hyperparameter tuning for the LightGBM Regressor model using GridSearchCV or RandomizedSearchCV to find the optimal set of parameters for improved performance.

"""

import lightgbm as lgb
from sklearn.model_selection import RandomizedSearchCV

# 2. Define the hyperparameter distributions
param_dist_lgbm = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7, 9, 10],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'num_leaves': [10, 20, 30, 40],
    'min_child_samples': [20, 30, 40, 50]
}

# 3. Instantiate a LGBMRegressor model
lgb_base_model = lgb.LGBMRegressor(random_state=42)

# 4. Instantiate RandomizedSearchCV
random_search_lgbm = RandomizedSearchCV(
    estimator=lgb_base_model,
    param_distributions=param_dist_lgbm,
    n_iter=10,  # Number of parameter settings that are sampled. Reduced for quicker execution.
    cv=3,       # Number of folds in cross-validation. Reduced for quicker execution.
    scoring='neg_mean_squared_error',
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# 5. Fit RandomizedSearchCV to the training data
random_search_lgbm.fit(X_train, y_train)

# 6. Print the best parameters found
print("Best parameters for LightGBM:", random_search_lgbm.best_params_)

"""## Evaluate and Summarize Optimized Models

### Subtask:
Retrain each model with their best found hyperparameters, make predictions on the test set, and recalculate RMSE, R-squared, and MAE. Then, provide a comparative summary of the optimized models' performances.

**Reasoning**:
First, I will retrieve the best hyperparameters for each model, then instantiate and retrain them, make predictions, and finally calculate and print the evaluation metrics (RMSE, R2, MAE) for each optimized model.
"""

from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
import lightgbm as lgb
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np

# 1. Retrieve the best parameters
best_params_rf = random_search_rf.best_params_
best_params_xgb = random_search_xgb.best_params_
best_params_lgbm = random_search_lgbm.best_params_

print("Best parameters for Random Forest:", best_params_rf)
print("Best parameters for XGBoost:", best_params_xgb)
print("Best parameters for LightGBM:", best_params_lgbm)

# 2. Instantiate new models with best parameters
optimized_rf_model = RandomForestRegressor(**best_params_rf, random_state=42)
optimized_xgb_model = XGBRegressor(**best_params_xgb, random_state=42)
optimized_lgbm_model = lgb.LGBMRegressor(**best_params_lgbm, random_state=42)

# 3. Fit each optimized model to the training data
print("\nRetraining Random Forest model...")
optimized_rf_model.fit(X_train, y_train)
print("Random Forest retrained.")

print("\nRetraining XGBoost model...")
optimized_xgb_model.fit(X_train, y_train)
print("XGBoost retrained.")

print("\nRetraining LightGBM model...")
optimized_lgbm_model.fit(X_train, y_train)
print("LightGBM retrained.")

# 4. Make predictions on the test set
y_pred_rf_tuned = optimized_rf_model.predict(X_test)
y_pred_xgb_tuned = optimized_xgb_model.predict(X_test)
y_pred_lgbm_tuned = optimized_lgbm_model.predict(X_test)

# 5 & 6. Calculate and print metrics for each optimized model
print("\n--- Optimized Random Forest Performance ---")
rmse_rf_tuned = np.sqrt(mean_squared_error(y_test, y_pred_rf_tuned))
r2_rf_tuned = r2_score(y_test, y_pred_rf_tuned)
mae_rf_tuned = mean_absolute_error(y_test, y_pred_rf_tuned)
print(f"RMSE: {rmse_rf_tuned:.4f}")
print(f"R-squared: {r2_rf_tuned:.4f}")
print(f"MAE: {mae_rf_tuned:.4f}")

print("\n--- Optimized XGBoost Performance ---")
rmse_xgb_tuned = np.sqrt(mean_squared_error(y_test, y_pred_xgb_tuned))
r2_xgb_tuned = r2_score(y_test, y_pred_xgb_tuned)
mae_xgb_tuned = mean_absolute_error(y_test, y_pred_xgb_tuned)
print(f"RMSE: {rmse_xgb_tuned:.4f}")
print(f"R-squared: {r2_xgb_tuned:.4f}")
print(f"MAE: {mae_xgb_tuned:.4f}")

print("\n--- Optimized LightGBM Performance ---")
rmse_lgbm_tuned = np.sqrt(mean_squared_error(y_test, y_pred_lgbm_tuned))
r2_lgbm_tuned = r2_score(y_test, y_pred_lgbm_tuned)
mae_lgbm_tuned = mean_absolute_error(y_test, y_pred_lgbm_tuned)
print(f"RMSE: {rmse_lgbm_tuned:.4f}")
print(f"R-squared: {r2_lgbm_tuned:.4f}")
print(f"MAE: {mae_lgbm_tuned:.4f}")

"""## Summary of Optimized Models Performance and Comparison

After hyperparameter tuning, the performance of the three models (Random Forest, XGBoost, and LightGBM) on the test set is as follows:

### Optimized Random Forest Model Metrics:
- **Root Mean Squared Error (RMSE):** 0.1755
- **R-squared (R2):** 0.3077
- **Mean Absolute Error (MAE):** 0.1415

### Optimized XGBoost Model Metrics:
- **Root Mean Squared Error (RMSE):** 0.1750
- **R-squared (R2):** 0.3117
- **Mean Absolute Error (MAE):** 0.1409

### Optimized LightGBM Model Metrics:
- **Root Mean Squared Error (RMSE):** 0.1747
- **R-squared (R2):** 0.3141
- **Mean Absolute Error (MAE):** 0.1406

### Comparative Analysis:

1.  **RMSE (Root Mean Squared Error):**
    -   LightGBM achieved the lowest RMSE at 0.1747, indicating its predictions are, on average, the closest to the actual prices. This is a slight improvement over XGBoost (0.1750) and Random Forest (0.1755).
    -   All three optimized models show a noticeable reduction in RMSE compared to their untuned versions, confirming the effectiveness of hyperparameter tuning.

2.  **R-squared (R2):**
    -   LightGBM again leads with the highest R-squared value of 0.3141. This means it explains approximately 31.41% of the variance in the 'Price' target variable, which is slightly better than XGBoost's 0.3117 and Random Forest's 0.3077.
    -   While improved, the R2 values for all models remain relatively low, suggesting that a significant portion of the price variance is still unexplained by the current features. This implies that there might be other influential factors not included in the dataset or that more complex feature engineering is required.

3.  **MAE (Mean Absolute Error):**
    -   LightGBM also delivered the lowest MAE at 0.1406, closely followed by XGBoost (0.1409) and Random Forest (0.1415). The MAE values are very close, suggesting similar average absolute errors across the optimized tree-based models.

### Conclusion:

Based on RMSE, R-squared, and MAE, the **Optimized LightGBM Regressor model** demonstrates the best overall performance among the three tuned models. It consistently achieved slightly better metrics, indicating a marginally superior ability to predict housing prices with the given features.

Compared to the initial untuned models, hyperparameter tuning has led to improvements across all three models, with the R-squared values increasing from ~0.20 to ~0.31 for Random Forest and XGBoost, and from ~0.31 to ~0.3141 for LightGBM. However, despite these improvements, the models still only explain a modest portion of the variance in housing prices. This suggests that while these models are well-tuned, the current feature set may not be comprehensive enough to capture all the complexities driving housing prices.

### Next Steps:
-   Further feature engineering, possibly creating new features from existing ones or incorporating external data sources, could significantly boost model performance.
-   Exploring more advanced ensemble techniques or stacking multiple models might also lead to better predictive power.
-   A deeper dive into the residuals of the LightGBM model could reveal specific areas where its predictions are weakest, guiding further improvements.
"""