from PyQt6 import QtCore, QtWidgets

class Ui_CustomerHome(object):
    def setupUi(self, CustomerHome):
        CustomerHome.setObjectName("CustomerHome")
        CustomerHome.resize(1280, 800)
        self.centralwidget = QtWidgets.QWidget(parent=CustomerHome)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_central = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_central.setObjectName("verticalLayout_central")
        self.hbox_topbar = QtWidgets.QHBoxLayout()
        self.hbox_topbar.setObjectName("hbox_topbar")
        spacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hbox_topbar.addItem(spacer)
        self.btn_logout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_logout.setObjectName("btn_logout")
        self.hbox_topbar.addWidget(self.btn_logout)
        self.verticalLayout_central.addLayout(self.hbox_topbar)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tab_predict = QtWidgets.QWidget()
        self.tab_predict.setObjectName("tab_predict")
        self.hbox_predict = QtWidgets.QHBoxLayout(self.tab_predict)
        self.hbox_predict.setObjectName("hbox_predict")
        self.group_input_house = QtWidgets.QGroupBox(parent=self.tab_predict)
        self.group_input_house.setObjectName("group_input_house")
        self.formLayout_inputs = QtWidgets.QFormLayout(self.group_input_house)
        self.formLayout_inputs.setObjectName("formLayout_inputs")
        self.label_area_income = QtWidgets.QLabel(parent=self.group_input_house)
        self.label_area_income.setObjectName("label_area_income")
        self.formLayout_inputs.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_area_income)
        self.input_area_income = QtWidgets.QLineEdit(parent=self.group_input_house)
        self.input_area_income.setObjectName("input_area_income")
        self.formLayout_inputs.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_area_income)
        self.label_house_age = QtWidgets.QLabel(parent=self.group_input_house)
        self.label_house_age.setObjectName("label_house_age")
        self.formLayout_inputs.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_house_age)
        self.input_house_age = QtWidgets.QLineEdit(parent=self.group_input_house)
        self.input_house_age.setObjectName("input_house_age")
        self.formLayout_inputs.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_house_age)
        self.label_num_rooms = QtWidgets.QLabel(parent=self.group_input_house)
        self.label_num_rooms.setObjectName("label_num_rooms")
        self.formLayout_inputs.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_num_rooms)
        self.input_num_rooms = QtWidgets.QLineEdit(parent=self.group_input_house)
        self.input_num_rooms.setObjectName("input_num_rooms")
        self.formLayout_inputs.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_num_rooms)
        self.label_num_bedrooms = QtWidgets.QLabel(parent=self.group_input_house)
        self.label_num_bedrooms.setObjectName("label_num_bedrooms")
        self.formLayout_inputs.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_num_bedrooms)
        self.input_num_bedrooms = QtWidgets.QLineEdit(parent=self.group_input_house)
        self.input_num_bedrooms.setObjectName("input_num_bedrooms")
        self.formLayout_inputs.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_num_bedrooms)
        self.label_population = QtWidgets.QLabel(parent=self.group_input_house)
        self.label_population.setObjectName("label_population")
        self.formLayout_inputs.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_population)
        self.input_population = QtWidgets.QLineEdit(parent=self.group_input_house)
        self.input_population.setObjectName("input_population")
        self.formLayout_inputs.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.input_population)
        self.hbox_predict.addWidget(self.group_input_house)
        self.group_predict_actions = QtWidgets.QGroupBox(parent=self.tab_predict)
        self.group_predict_actions.setObjectName("group_predict_actions")
        self.vbox_predict_actions = QtWidgets.QVBoxLayout(self.group_predict_actions)
        self.vbox_predict_actions.setObjectName("vbox_predict_actions")

        # Nhãn "Predicted Price:" + kết quả
        self.label_pred_price = QtWidgets.QLabel(parent=self.group_predict_actions)
        self.label_pred_price.setObjectName("label_pred_price")
        self.vbox_predict_actions.addWidget(self.label_pred_price)

        self.lbl_prediction_result = QtWidgets.QLabel(parent=self.group_predict_actions)
        self.lbl_prediction_result.setObjectName("lbl_prediction_result")
        self.lbl_prediction_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vbox_predict_actions.addWidget(self.lbl_prediction_result)

        # Nút dự đoán và export
        self.btn_predict = QtWidgets.QPushButton(parent=self.group_predict_actions)
        self.btn_predict.setObjectName("btn_predict")
        self.vbox_predict_actions.addWidget(self.btn_predict)
        self.btn_export_report = QtWidgets.QPushButton(parent=self.group_predict_actions)
        self.btn_export_report.setObjectName("btn_export_report")
        self.vbox_predict_actions.addWidget(self.btn_export_report)
        self.hbox_predict.addWidget(self.group_predict_actions)
        self.tabWidget.addTab(self.tab_predict, "Dự đoán Giá")
        self.tab_history = QtWidgets.QWidget()
        self.tab_history.setObjectName("tab_history")
        self.vbox_history = QtWidgets.QVBoxLayout(self.tab_history)
        self.vbox_history.setObjectName("vbox_history")
        self.group_history_chart = QtWidgets.QGroupBox(parent=self.tab_history)
        self.group_history_chart.setObjectName("group_history_chart")
        self.vbox_history_chart = QtWidgets.QVBoxLayout(self.group_history_chart)
        self.vbox_history_chart.setObjectName("vbox_history_chart")
        self.chart_view_history = QtWidgets.QWidget(parent=self.group_history_chart)
        self.chart_view_history.setObjectName("chart_view_history")
        self.vbox_history_chart.addWidget(self.chart_view_history)
        self.vbox_history.addWidget(self.group_history_chart)
        self.group_history_details = QtWidgets.QGroupBox(parent=self.tab_history)
        self.group_history_details.setObjectName("group_history_details")
        self.vbox_history_details = QtWidgets.QVBoxLayout(self.group_history_details)
        self.vbox_history_details.setObjectName("vbox_history_details")
        self.table_history = QtWidgets.QTableWidget(parent=self.group_history_details)
        self.table_history.setObjectName("table_history")
        self.vbox_history_details.addWidget(self.table_history)
        self.vbox_history.addWidget(self.group_history_details)
        self.tabWidget.addTab(self.tab_history, "Lịch sử Dự đoán")
        CustomerHome.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CustomerHome)
        self.menubar.setObjectName("menubar")
        CustomerHome.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CustomerHome)
        self.statusbar.setObjectName("statusbar")
        CustomerHome.setStatusBar(self.statusbar)
        self.retranslateUi(CustomerHome)
        QtCore.QMetaObject.connectSlotsByName(CustomerHome)

    def retranslateUi(self, CustomerHome):
        _translate = QtCore.QCoreApplication.translate
        CustomerHome.setWindowTitle(_translate("CustomerHome", "Customer - ML Price Predictor"))
        self.btn_logout.setText(_translate("CustomerHome", "Logout"))
        self.group_input_house.setTitle(_translate("CustomerHome", "Input Features"))
        self.label_area_income.setText(_translate("CustomerHome", "Avg Area Income"))
        self.label_house_age.setText(_translate("CustomerHome", "Avg Area House Age"))
        self.label_num_rooms.setText(_translate("CustomerHome", "Avg Area Number of Rooms"))
        self.label_num_bedrooms.setText(_translate("CustomerHome", "Avg Area Number of Bedrooms"))
        self.label_population.setText(_translate("CustomerHome", "Area Population"))
        self.group_predict_actions.setTitle(_translate("CustomerHome", "Results & Actions"))
        self.label_pred_price.setText(_translate("CustomerHome", "Predicted Price:"))
        self.lbl_prediction_result.setText(_translate("CustomerHome", "..."))
        self.btn_predict.setText(_translate("CustomerHome", "Predict Price"))
        self.btn_export_report.setText(_translate("CustomerHome", "Export Report (CSV)"))
        # Lịch sử
        self.group_history_actions = QtWidgets.QGroupBox(parent=self.tab_history)
        self.group_history_actions.setObjectName("group_history_actions")
        self.vbox_history_actions = QtWidgets.QVBoxLayout(self.group_history_actions)
        self.vbox_history_actions.setObjectName("vbox_history_actions")
        self.btn_delete_history = QtWidgets.QPushButton(parent=self.group_history_actions)
        self.btn_delete_history.setObjectName("btn_delete_history")
        self.vbox_history_actions.addWidget(self.btn_delete_history)
        self.btn_clear_history = QtWidgets.QPushButton(parent=self.group_history_actions)
        self.btn_clear_history.setObjectName("btn_clear_history")
        self.vbox_history_actions.addWidget(self.btn_clear_history)
        self.btn_export_history = QtWidgets.QPushButton(parent=self.group_history_actions)
        self.btn_export_history.setObjectName("btn_export_history")
        self.vbox_history_actions.addWidget(self.btn_export_history)
        self.vbox_history.addWidget(self.group_history_actions)
        self.group_history_chart.setTitle(_translate("CustomerHome", "Trend"))
        self.group_history_details.setTitle(_translate("CustomerHome", "Details"))
        self.group_history_actions.setTitle(_translate("CustomerHome", "Actions"))
        self.btn_delete_history.setText(_translate("CustomerHome", "Delete Selected"))
        self.btn_clear_history.setText(_translate("CustomerHome", "Clear All"))
        self.btn_export_history.setText(_translate("CustomerHome", "Export History (CSV)"))