from PyQt6 import QtCore, QtWidgets

class Ui_CustomerHome(object):
    def setupUi(self, CustomerHome):
        CustomerHome.setObjectName("CustomerHome")
        CustomerHome.resize(1280, 800)
        self.centralwidget = QtWidgets.QWidget(parent=CustomerHome)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_central = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_central.setObjectName("verticalLayout_central")
        self.widget_topbar = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_topbar.setObjectName("widget_topbar")
        self.hbox_topbar = QtWidgets.QHBoxLayout(self.widget_topbar)
        self.hbox_topbar.setObjectName("hbox_topbar")
        self.hbox_topbar.setContentsMargins(12, 8, 12, 8)
        left_spacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hbox_topbar.addItem(left_spacer)
        self.lbl_header_title = QtWidgets.QLabel(parent=self.widget_topbar)
        self.lbl_header_title.setObjectName("lbl_header_title")
        self.lbl_header_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_header_title.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred))
        self.hbox_topbar.addWidget(self.lbl_header_title)
        right_spacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hbox_topbar.addItem(right_spacer)
        self.btn_toggle_theme = QtWidgets.QPushButton(parent=self.widget_topbar)
        self.btn_toggle_theme.setObjectName("btn_toggle_theme")
        self.hbox_topbar.addWidget(self.btn_toggle_theme)
        self.btn_logout = QtWidgets.QPushButton(parent=self.widget_topbar)
        self.btn_logout.setObjectName("btn_logout")
        self.hbox_topbar.addWidget(self.btn_logout)
        self.verticalLayout_central.addWidget(self.widget_topbar)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.verticalLayout_central.addWidget(self.tabWidget)
        self.tab_predict = QtWidgets.QWidget()
        self.tab_predict.setObjectName("tab_predict")
        self.vbox_predict = QtWidgets.QVBoxLayout(self.tab_predict)
        self.vbox_predict.setObjectName("vbox_predict")
        # Loại bỏ 2 khung trên, chỉ giữ House Input Form

        # Inline House Input Form group (replace popup button)
        self.group_house_inline = QtWidgets.QGroupBox(parent=self.tab_predict)
        self.group_house_inline.setObjectName("group_house_inline")
        self.vbox_house_inline = QtWidgets.QVBoxLayout(self.group_house_inline)
        self.vbox_house_inline.setObjectName("vbox_house_inline")
        # Container where the HouseInputForm widget will be embedded
        self.widget_house_inline_container = QtWidgets.QWidget(parent=self.group_house_inline)
        self.widget_house_inline_container.setObjectName("widget_house_inline_container")
        self.vbox_house_inline.addWidget(self.widget_house_inline_container)
        self.vbox_predict.addWidget(self.group_house_inline)
        self.group_price_chart = QtWidgets.QGroupBox(parent=self.tab_predict)
        self.group_price_chart.setObjectName("group_price_chart")
        self.vbox_price_chart = QtWidgets.QVBoxLayout(self.group_price_chart)
        self.vbox_price_chart.setObjectName("vbox_price_chart")
        self.hbox_price_charts = QtWidgets.QHBoxLayout()
        self.hbox_price_charts.setObjectName("hbox_price_charts")
        self.chart_view_price_trend = QtWidgets.QWidget(parent=self.group_price_chart)
        self.chart_view_price_trend.setObjectName("chart_view_price_trend")
        self.chart_view_price_breakdown = QtWidgets.QWidget(parent=self.group_price_chart)
        self.chart_view_price_breakdown.setObjectName("chart_view_price_breakdown")
        self.hbox_price_charts.addWidget(self.chart_view_price_trend)
        self.hbox_price_charts.addWidget(self.chart_view_price_breakdown)
        self.vbox_price_chart.addLayout(self.hbox_price_charts)
        self.vbox_predict.addWidget(self.group_price_chart)
        
        self.tabWidget.addTab(self.tab_predict, "Dự đoán Giá")
        self.tab_history = QtWidgets.QWidget()
        self.tab_history.setObjectName("tab_history")
        self.vbox_history = QtWidgets.QVBoxLayout(self.tab_history)
        self.vbox_history.setObjectName("vbox_history")
        self.group_history_chart = QtWidgets.QGroupBox(parent=self.tab_history)
        self.group_history_chart.setObjectName("group_history_chart")
        self.vbox_history_chart = QtWidgets.QVBoxLayout(self.group_history_chart)
        self.vbox_history_chart.setObjectName("vbox_history_chart")
        self.chart_view_history = QtWidgets.QWidget(parent=self.group_history_chart)
        self.chart_view_history.setObjectName("chart_view_history")
        self.vbox_history_chart.addWidget(self.chart_view_history)
        self.vbox_history.addWidget(self.group_history_chart)
        self.group_history_details = QtWidgets.QGroupBox(parent=self.tab_history)
        self.group_history_details.setObjectName("group_history_details")
        self.vbox_history_details = QtWidgets.QVBoxLayout(self.group_history_details)
        self.vbox_history_details.setObjectName("vbox_history_details")
        self.table_history = QtWidgets.QTableWidget(parent=self.group_history_details)
        self.table_history.setObjectName("table_history")
        self.vbox_history_details.addWidget(self.table_history)
        self.vbox_history.addWidget(self.group_history_details)
        self.tabWidget.addTab(self.tab_history, "Lịch sử Dự đoán")

        self.tab_map = QtWidgets.QWidget()
        self.tab_map.setObjectName("tab_map")
        self.vbox_map = QtWidgets.QVBoxLayout(self.tab_map)
        self.vbox_map.setObjectName("vbox_map")
        self.chart_view_city_map = QtWidgets.QWidget(parent=self.tab_map)
        self.chart_view_city_map.setObjectName("chart_view_city_map")
        self.vbox_map.addWidget(self.chart_view_city_map)
        self.tabWidget.addTab(self.tab_map, "Bản đồ")

        # Tab Chatbot
        self.tab_chatbot = QtWidgets.QWidget()
        self.tab_chatbot.setObjectName("tab_chatbot")
        self.vbox_chatbot = QtWidgets.QVBoxLayout(self.tab_chatbot)
        self.vbox_chatbot.setObjectName("vbox_chatbot")
        self.group_chatbot = QtWidgets.QGroupBox(parent=self.tab_chatbot)
        self.group_chatbot.setObjectName("group_chatbot")
        self.vbox_group_chatbot = QtWidgets.QVBoxLayout(self.group_chatbot)
        self.vbox_group_chatbot.setObjectName("vbox_group_chatbot")
        self.btn_start_chatbot = QtWidgets.QPushButton(parent=self.group_chatbot)
        self.btn_start_chatbot.setObjectName("btn_start_chatbot")
        self.vbox_group_chatbot.addWidget(self.btn_start_chatbot)
        self.lbl_chatbot_url = QtWidgets.QLabel(parent=self.group_chatbot)
        self.lbl_chatbot_url.setObjectName("lbl_chatbot_url")
        self.lbl_chatbot_url.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.vbox_group_chatbot.addWidget(self.lbl_chatbot_url)
        self.widget_chatbot_web = QtWidgets.QWidget(parent=self.group_chatbot)
        self.widget_chatbot_web.setObjectName("widget_chatbot_web")
        self.vbox_group_chatbot.addWidget(self.widget_chatbot_web)
        self.vbox_chatbot.addWidget(self.group_chatbot)
        self.tabWidget.addTab(self.tab_chatbot, "Chatbot")

        CustomerHome.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CustomerHome)
        self.menubar.setObjectName("menubar")
        CustomerHome.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CustomerHome)
        self.statusbar.setObjectName("statusbar")
        CustomerHome.setStatusBar(self.statusbar)
        self.retranslateUi(CustomerHome)
        QtCore.QMetaObject.connectSlotsByName(CustomerHome)

    def retranslateUi(self, CustomerHome):
        _translate = QtCore.QCoreApplication.translate
        CustomerHome.setWindowTitle(_translate("CustomerHome", "Customer - ML Price Predictor"))
        self.lbl_header_title.setText(_translate("CustomerHome", "HOUSE PRICE PREDICTION SYSTEM"))
        self.btn_toggle_theme.setText(_translate("CustomerHome", "Toggle Theme"))
        self.btn_logout.setText(_translate("CustomerHome", "Logout"))
        # Đã bỏ khung Input Features và Results & Actions
        # Lịch sử
        self.group_history_actions = QtWidgets.QGroupBox(parent=self.tab_history)
        self.group_history_actions.setObjectName("group_history_actions")
        self.vbox_history_actions = QtWidgets.QVBoxLayout(self.group_history_actions)
        self.vbox_history_actions.setObjectName("vbox_history_actions")
        self.btn_delete_history = QtWidgets.QPushButton(parent=self.group_history_actions)
        self.btn_delete_history.setObjectName("btn_delete_history")
        self.vbox_history_actions.addWidget(self.btn_delete_history)
        self.btn_clear_history = QtWidgets.QPushButton(parent=self.group_history_actions)
        self.btn_clear_history.setObjectName("btn_clear_history")
        self.vbox_history_actions.addWidget(self.btn_clear_history)
        self.btn_export_history = QtWidgets.QPushButton(parent=self.group_history_actions)
        self.btn_export_history.setObjectName("btn_export_history")
        self.vbox_history_actions.addWidget(self.btn_export_history)
        self.vbox_history.addWidget(self.group_history_actions)
        self.group_history_chart.setTitle(_translate("CustomerHome", "Trend"))
        self.group_history_details.setTitle(_translate("CustomerHome", "Details"))
        self.group_history_actions.setTitle(_translate("CustomerHome", "Actions"))
        self.btn_delete_history.setText(_translate("CustomerHome", "Delete Selected"))
        self.btn_clear_history.setText(_translate("CustomerHome", "Clear All"))
        self.btn_export_history.setText(_translate("CustomerHome", "Export History (CSV)"))
        self.group_house_inline.setTitle(_translate("CustomerHome", "House Input Form"))
        self.group_price_chart.setTitle(_translate("CustomerHome", "Price Trend (2015–2035)"))
        self.group_chatbot.setTitle(_translate("CustomerHome", "Tư vấn giá nhà (Chatbot)"))
        self.btn_start_chatbot.setText(_translate("CustomerHome", "Start Chatbot"))
        self.lbl_chatbot_url.setText(_translate("CustomerHome", "URL: chưa khởi động"))